### ISSUE TITLE
Videosort error when using RSS

### ISSUE THREAD

**Issue by Helieux** [nzbgetcom/nzbget#434]
Videosort has been working well for me until recently when I tried to use it to rename file from RSS. 

NZB: [Link](https://animetosho.org/storage/nzbs/000a16d6/BLEACH.Thousand-Year.Blood.War.S01E29.THE.DARK.ARM.1080p.DSNP.WEB-DL.DUAL.AAC2.0.H.264.MSubs-ToonsHub.nzb.gz)
RSS: [Link](https://feed.animetosho.org/rss2?q=%5BToonsHub%5D+BLEACH+Thousand-Year+Blood+War+S01E29+1080p+DSNP+WEB-DL+AAC2+0+H+264+%28BLEACH+Sennen+Kessen-hen%2C+Dual-Audio%2C+Multi-Subs%29)

Download via RSS will cause the pp failure below: 

```
error	Mon Nov 18 2024 17:21:04	Post-process-script VideoSort for [ToonsHub] BLEACH Thousand-Year Blood War S01E29 1080p DSNP WEB-DL AAC2.0 H.264 (BLEACH_ Sennen Kessen-hen, Dual-Audio, Multi-Subs) failed
error	Mon Nov 18 2024 17:21:04	Video Sort: expected string or bytes-like object, got 'list'
error	Mon Nov 18 2024 17:21:04	Video Sort: Failed: BLEACH.Thousand-Year.Blood.War.S01E29.THE.DARK.ARM.1080p.DSNP.WEB-DL.DUAL.AAC2.0.H.264.MSubs-ToonsHub.mkv
info	Mon Nov 18 2024 17:21:04	Video Sort: TypeError: expected string or bytes-like object, got 'list'
info	Mon Nov 18 2024 17:21:04	Video Sort: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
info	Mon Nov 18 2024 17:21:04	Video Sort: return _compile(pattern, flags).sub(repl, string, count)
info	Mon Nov 18 2024 17:21:04	Video Sort: File "C:\Program Files\Python312\Lib\re\__init__.py", line 186, in sub
info	Mon Nov 18 2024 17:21:04	Video Sort: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
info	Mon Nov 18 2024 17:21:04	Video Sort: title = re.sub(r"[\"\:\?\*\\\/\<\>\|]", " ", name)
info	Mon Nov 18 2024 17:21:04	Video Sort: File "D:\NZBGet\Scripts\VideoSort\main.py", line 427, in get_titles
info	Mon Nov 18 2024 17:21:04	Video Sort: ^^^^^^^^^^^^^^^^^^^^^^^^
info	Mon Nov 18 2024 17:21:04	Video Sort: show_tname, show_tname_two, show_tname_three = get_titles(series, True)
info	Mon Nov 18 2024 17:21:04	Video Sort: File "D:\NZBGet\Scripts\VideoSort\main.py", line 634, in add_series_mapping
info	Mon Nov 18 2024 17:21:04	Video Sort: add_series_mapping(guess, mapping)
info	Mon Nov 18 2024 17:21:04	Video Sort: File "D:\NZBGet\Scripts\VideoSort\main.py", line 1054, in construct_path
info	Mon Nov 18 2024 17:21:04	Video Sort: ^^^^^^^^^^^^^^^^^^^^^^^^
info	Mon Nov 18 2024 17:21:04	Video Sort: new_path = construct_path(old_path)
info	Mon Nov 18 2024 17:21:04	Video Sort: File "D:\NZBGet\Scripts\VideoSort\main.py", line 1165, in <module>
info	Mon Nov 18 2024 17:21:04	Video Sort: Traceback (most recent call last):
info	Mon Nov 18 2024 17:21:03	Executing post-process-script VideoSort for [ToonsHub] BLEACH Thousand-Year Blood War S01E29 1080p DSNP WEB-DL AAC2.0 H.264 (BLEACH_ Sennen Kessen-hen, Dual-Audio, Multi-Subs)
```

**Comment by dnzbk** [comment]
Thanks, I'll look into it. 
And thanks for the link to nzb and RSS - they'll be verry useful but please share such links to denis@nzbget.com next time.

**Comment by Helieux** [comment]
Python v3.12.6

**Comment by Helieux** [comment]
> Thanks, I'll look into it. And thanks for the link to nzb and RSS - they'll be verry useful but please share such links to [denis@nzbget.com](mailto:denis@nzbget.com) next time.

Thanks, I will remove the filename for privacy in the original post.

**Comment by dnzbk** [comment]
[Fix TypeError on RSS downloads and preserve Unicode in titles](https://github.com/nzbgetcom/Extension-VideoSort/pull/21)
