### ISSUE TITLE
FailureLink logs warning message about some deprecation in Python 3.13

### ISSUE THREAD

**Issue by dnzbk** [nzbgetcom/nzbget#75]
E.g. FailureLink.py:101: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
Apparently, FailureLink won't work with Python3.13

**Comment by MattPark** [comment]
For me, Failurelink fails more than that and causes postprocessing to "fail"
```
ERROR | Sat Mar 02 2024 11:26:17 | Post-process-script FailureLink for Open.Source.Linux.Movie.HEVC.1080p.BluRay.DTS.265-LEGi0N failed (terminated with unknown status)
-- | -- | --
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: TypeError: a bytes-like object is required, not 'str'
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: ^^^^^^^^^^^^^^^^^^^^
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: if 'avprobe' in FFPROBE:
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: File "/config/scripts/FailureLink/main.py", line 133, in getVideoDetails
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: ^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: video_details, result = getVideoDetails(videofile)
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: File "/config/scripts/FailureLink/main.py", line 110, in isVideoGood
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: ^^^^^^^^^^^^^^^^^^^^^
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: if isVideoGood(filepath):
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: File "/config/scripts/FailureLink/main.py", line 176, in corruption_check
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: ^^^^^^^^^^^^^^^^^^
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: corrupt = corruption_check()
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: File "/config/scripts/FailureLink/main.py", line 332, in main
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: main()
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: File "/config/scripts/FailureLink/main.py", line 391, in <module>
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: Traceback (most recent call last):
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: Checking [4796628f788c498aa1a2310124bc2f33.mkv] for corruption, please stand by ...
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: import cgi
INFO | Sat Mar 02 2024 11:26:17 | Failure Link: /config/scripts/FailureLink/main.py:30: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
```

**Comment by MattPark** [comment]
I'm rocking the official docker image so 3.11.6

**Comment by dnzbk** [comment]
@MattPark 

Failurelink should be fixed now.
Сonsider upgrading to v4.1 using Extension Manager, thanks.

**Comment by MattPark** [comment]
Will do,  thanks!
